dist: xenial

services:
  - docker

before_install:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - dockerName="$DOCKER_USERNAME/rtl_433tomqtt:$TRAVIS_TAG" 
   - docker build -t $dockerName .
   - docker images
   - docker push $dockerName

deploy:
  provider: script
  script: docker push $dockerName
  on:
    branch: master
    tags: true

